### ISSUE TITLE
links to other ".org" files not exporting correctly

### ISSUE THREAD

**Issue by jtoss** [msnoigrs/ox-rst#34]
Hi, 
I noticed that links to other ".org" files are not correctly exported:
`[[file:somefile.org]] `
is exported to 
 ` 'somefile. <somefile.>'_` 

Normally we would expect it to create something like `'somefile.rst <somefile.rst>'_` right ?

**Comment by jtoss** [comment]
For the moment I'm using the following workaround to fix this issue. 
Just put this code into your init.el 
```elisp
     
(defun fix-rst-link-format (text backend info)
  "Temporary fix for bug https://github.com/masayuko/ox-rst/issues/34"
  (when (org-export-derived-backend-p backend 'rst)
    (replace-regexp-in-string "\\(\\.\\)[ >]"  ".rst" text nil nil 1)))

(add-to-list 'org-export-filter-link-functions
             'fix-rst-link-format)
```

**Comment by msnoigrs** [comment]
Sorry for long silence.
