### ISSUE TITLE
Multi-line footnotes

### ISSUE THREAD

**Issue by schuach** [msnoigrs/ox-rst#38]
Thanks for this package!

I have installed ox-nikola (and therefore ox-rst) via MELPA.

Whenn footnotes span over multiple lines, the second and subsequent line are not indented so there are errors in the resulting html.

org input:
```
Testtext[fn:1]

[fn:1] First line of footnote text
    Second line of footnote text
    Third line of footnote text
```

rst output:
```
Testtext [1]_ 


.. [1] First line of footnote text
Second line of footnote text
Third line of footnote text
```

Is this a bug or is there another way to achieve the desired output?

Thanks and best regards
Stefan

**Comment by msnoigrs** [comment]
Thank you for your report.
I dont' have time to look into this at the moment. When I have time I will check this.

**Comment by msnoigrs** [comment]
Please try it.

**Comment by schuach** [comment]
That was really quick!

It works fine now!

Thanks and best regards
Stefan
