### ISSUE TITLE
Using ox-rst as a cli script

### ISSUE THREAD

**Issue by jgarte** [msnoigrs/ox-rst#55]
Hi,

Has anyone tried using ox-rst as a cli script?

I'd like to just run a script from the command line that is called `org2rst`
and uses ox-rst underneath. So, an elisp script.

**Comment by andrewtmorgan** [comment]
This can be done with `emacs`'s batch command:

```
emacs $orgfile --batch --eval="(load \"/path/to/ox-rst.el\")" -f org-rst-export-to-rst --kill
```

which produces an `rst` file in the same location as `$orgfile`. 

You can alternatively load your normal `init` instead of just `ox-rst.el` if you need other options. I only load that single file on batch startup to keep it as fast as possible.

**Comment by jgarte** [comment]
Thanks @andrewtmorgan  That's awesome!
